graph TD
    A["PresentationLayer
+ServiceAPI"]

    A -->|Facade Pattern| B

    B["BusinessLogicLayer
+User
+Place
+Review
+Amenity"]

    B -->|Database Operations| C

    C["PersistenceLayer
+DatabaseAccess
+Repository"]
